/*
 * Quahog_Shell.java
 */

import java.awt.*;

/*
 * CPS 150
 * Algorithms & Programming I
 * Lab Project: The Quahog Shell
 * 
 *   Make sure to add all graphics code in the paint method below,
 *   NOT in the main method.
 * 
 *   NOTE: DO NOT rename this class or file!!!  Doing so will cause
 *         this program to stop working!!!
 * 
 * Name:Ryan Zmuda
 * 
 */
 
@SuppressWarnings("serial")
public class Quahog_Shell extends javax.swing.JFrame
{

    public void paint(Graphics g)
    {
        // draw the window title, menu, buttons
        super.paint(g);

        // get the Graphics context for the canvas
        Graphics pen = canvas.getGraphics();

        // *** add pen Graphics method calls after this line ***
        int r = (int)Math.floor(Math.random()*(6-3+1)+3);
        for(int i=1;i<r;i++) {
        	pen.drawOval(300 - (25*i), 200 - (20*i), 50 * i, 20 * i);
        }
        
        /**
         * *********************************************************
         * WARNING!!! DO NOT ADD OR MODIFY CODE BELOW THIS LINE!!! *
         * *********************************************************
         */
    } // end paint

    /**
     * Creates new form NB_Quahog_Shell2
     */
    public Quahog_Shell()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the NB_Quahog_Shell2 Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        canvas = new javax.swing.JPanel();
        resetBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("My Drawing Form");

        canvas.setBackground(new java.awt.Color(255, 255, 255));
        canvas.setLayout(new java.awt.BorderLayout());
        getContentPane().add(canvas, java.awt.BorderLayout.CENTER);

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                resetBtnActionPerformed(evt);
            }
        });
        getContentPane().add(resetBtn, java.awt.BorderLayout.PAGE_END);

        setSize(new java.awt.Dimension(816, 639));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        repaint();
    }//GEN-LAST:event_resetBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Quahog_Shell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Quahog_Shell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Quahog_Shell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Quahog_Shell.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Quahog_Shell().setVisible(true);
            }
        });
    } // end main method

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel canvas;
    private javax.swing.JButton resetBtn;
    // End of variables declaration//GEN-END:variables
} // end Quahog_Shell class
